version: '2'
volumes:
  sql: {}

services:
  skillviz:
    extends:
      file: common.yml
      service: skillviz
  database:
    image: postgres
    container_name: database
    environment:
      PGDATA: "/var/lib/postgresql/data/rebase"
    volumes:
     - sql:/var/lib/postgresql/data/rebase
  proxy:
    extends:
      file: "${PROXY_REPO}/layouts/common.yml"
      service: proxy
  rest_api:
    extends:
      file: "${REST_API_REPO}/layouts/dev.yml"
      service: rest_api
  rq_dashboard:
    extends:
      file: "${JOB_QUEUE_REPO}/layouts/common.yml"
      service: rq_dashboard
  redis:
    extends:
      file: "${JOB_QUEUE_REPO}/layouts/common.yml"
      service: redis
  default_queue:
    extends:
      file: "${JOB_QUEUE_REPO}/layouts/common.yml"
      service: default_queue
    environment:
      LOG_LEVEL: "DEBUG"
  private_github_crawler:
    extends:
      file: "${JOB_QUEUE_REPO}/layouts/dev.yml"
      service: private_github_crawler
    environment:
      LOG_LEVEL: "DEBUG"
  public_github_crawler:
    extends:
      file: "${JOB_QUEUE_REPO}/layouts/common.yml"
      service: public_github_crawler
    environment:
      LOG_LEVEL: "DEBUG"
  population_analyzer:
    extends:
      file: "${JOB_QUEUE_REPO}/layouts/common.yml"
      service: population_analyzer
    environment:
      LOG_LEVEL: "DEBUG"
  logserver:
    extends:
      file: "${LOGSERVER_REPO}/layouts/common.yml"
      service: logserver
    environment:
      LOG_LEVEL: "DEBUG"


